server:
  port: 9101

#turbine:
#  app-config: MICROSERVICE-PROVIDER-PRODUCT #需要收集信息的服务名
#  cluster-name-expression: new String("default")
#  combine-host-port: true    # 同一主机上的服务通过主机名和端口号的组合来进行区分，默认以host来区分